version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql_container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: measuremeinmeteredlines
    volumes:
      - /srv/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my_mysql_network

networks:
  my_mysql_network:
